### ISSUE TITLE
[BUG / Error]

### ISSUE THREAD

**Issue by Abadima** [Sigma-Production/PteroFreeStuffinstaller#56]
**Did you run on a clean panel?**
(Pterodactyl did a major refactor a while back)
**YES**

**Describe the bug**
It fails to install any theme on **V1.11.2**, with an error message, followed by the panel breaking.

**To Reproduce**
1. Run the script
2. Select any `DarkNColor` Theme
3. Let it run

**Expected behavior**
I have expected this to not error, and show the chanages

**Screenshots**
![image](https://user-images.githubusercontent.com/39747270/211064816-29a4c856-dcbf-46a6-b701-cf15181e9cf7.png)

**Pterodactyl error log**
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/var/www/pterodactyl/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/var/www/pterodactyl/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/var/www/pterodactyl/node_modules/webpack/lib/NormalModule.js:471:10)
    at /var/www/pterodactyl/node_modules/webpack/lib/NormalModule.js:503:5
    at /var/www/pterodactyl/node_modules/webpack/lib/NormalModule.js:358:12
    at /var/www/pterodactyl/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/var/www/pterodactyl/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/var/www/pterodactyl/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /var/www/pterodactyl/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/var/www/pterodactyl/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/pterodactyl/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by finnie2006** [comment]
It seems like something is wrong on your side, try looking at https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported

**Comment by Abadima** [comment]
Thanks!
Running `export NODE_OPTIONS=--openssl-legacy-provider` fixed my issue :)
